language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-29.0.2
    - android-29
    - extra-android-m2repository

before_install:
  - yes | sdkmanager "platforms;android-29"

script:
  - ./gradlew build test

deploy:
  provider: script
  script: ./gradlew bintrayUpload
  on:
    tags: true
